x = int(input("Enter value of x: "))
y = int(input("Enter value of y: "))
print("Addition:", x + y)
print("Subtraction:", x - y)
print("Multiplication:", x * y)
print("Division:", x / y)
print("Power:", x ** y)
print("F Division:", x // y)
print("Modulo:", x % y)